//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "doc_diff_detail")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub record_id: i64,
    pub position_type: i8,
    pub target_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub content: Option<String>,
    pub modify_type: i8,
    pub gmt_create: Option<DateTime>,
    pub gmt_modified: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
