//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "doc_info")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    #[sea_orm(unique)]
    pub data_id: String,
    pub md5: String,
    pub name: String,
    #[sea_orm(column_type = "custom(\"LONGTEXT\")", nullable)]
    pub description: Option<String>,
    pub author: String,
    pub r#type: i8,
    pub url: String,
    pub version: Option<String>,
    pub http_method: String,
    pub content_type: String,
    pub deprecated: Option<String>,
    pub is_folder: i8,
    pub parent_id: u64,
    pub module_id: u64,
    pub is_use_global_headers: i8,
    pub is_use_global_params: i8,
    pub is_use_global_returns: i8,
    pub is_request_array: i8,
    pub is_response_array: i8,
    pub request_array_type: String,
    pub response_array_type: String,
    pub create_mode: i8,
    pub modify_mode: i8,
    pub creator_id: u64,
    pub creator_name: String,
    pub modifier_id: u64,
    pub modifier_name: String,
    pub order_index: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub remark: Option<String>,
    pub is_show: i8,
    pub is_deleted: i8,
    pub is_locked: i8,
    pub status: Option<i8>,
    pub gmt_create: Option<DateTime>,
    pub gmt_modified: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
