//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "doc_snapshot")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub doc_id: u64,
    pub md5: String,
    pub modifier_name: String,
    pub modifier_time: DateTime,
    #[sea_orm(column_type = "Text", nullable)]
    pub content: Option<String>,
    pub gmt_create: Option<DateTime>,
    pub gmt_modified: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
