//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "doc_diff_record")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub doc_id: u64,
    pub md5_old: String,
    pub md5_new: String,
    pub modify_source: i8,
    pub modify_user_id: i64,
    pub modify_nickname: String,
    pub modify_type: i8,
    pub modify_time: Option<DateTime>,
    pub gmt_create: Option<DateTime>,
    pub gmt_modified: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
