//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "mock_config")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub name: String,
    pub data_id: String,
    pub path: String,
    pub ip: String,
    #[sea_orm(column_type = "Text")]
    pub request_data: String,
    pub request_data_type: i8,
    pub http_status: i32,
    pub delay_mills: i32,
    pub result_type: i8,
    #[sea_orm(column_type = "Text")]
    pub response_headers: String,
    #[sea_orm(column_type = "Text")]
    pub response_body: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub mock_script: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub mock_result: Option<String>,
    pub doc_id: i64,
    pub remark: String,
    pub creator_id: i64,
    pub creator_name: String,
    pub modifier_id: i64,
    pub modifier_name: Option<String>,
    pub is_deleted: i8,
    pub gmt_create: Option<DateTime>,
    pub gmt_modified: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
