//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "module")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub name: String,
    pub project_id: u64,
    pub r#type: i8,
    pub import_url: String,
    pub basic_auth_username: String,
    pub basic_auth_password: String,
    #[sea_orm(unique)]
    pub token: String,
    pub create_mode: i8,
    pub modify_mode: i8,
    pub creator_id: u64,
    pub modifier_id: u64,
    pub order_index: i32,
    pub is_deleted: i8,
    pub gmt_create: Option<DateTime>,
    pub gmt_modified: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
