//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "module_config")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub module_id: u64,
    pub r#type: i8,
    pub config_key: String,
    pub config_value: String,
    pub extend_id: u64,
    pub description: String,
    pub is_deleted: i8,
    pub gmt_create: Option<DateTime>,
    pub gmt_modified: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
