//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "module_environment_param")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    #[sea_orm(unique)]
    pub data_id: String,
    pub name: String,
    pub r#type: String,
    pub required: i8,
    pub max_length: String,
    pub example: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub enum_id: u64,
    pub environment_id: u64,
    pub parent_id: u64,
    pub style: i8,
    pub create_mode: i8,
    pub modify_mode: i8,
    pub creator_id: u64,
    pub creator_name: String,
    pub modifier_id: u64,
    pub modifier_name: String,
    pub order_index: i32,
    pub is_deleted: i8,
    pub gmt_create: Option<DateTime>,
    pub gmt_modified: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
