//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "push_ignore_field")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub module_id: u64,
    pub data_id: String,
    pub field_name: String,
    pub field_description: String,
    pub gmt_create: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
