//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_dingtalk_info")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub nick: String,
    pub name: String,
    pub email: String,
    pub userid: String,
    #[sea_orm(unique)]
    pub unionid: String,
    pub openid: String,
    pub user_info_id: u64,
    pub gmt_create: Option<DateTime>,
    pub gmt_modified: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
